development:
  adapter: sqlite3
  database: db/school-dev.sqlite3

test:
  adapter: sqlite3
  database: db/school-test.sqlite3

production:
  adapter: sqlite3
  database: db/school-production.sqlite3
